// Generated by CoffeeScript 1.7.1
var Entity;

Entity = (function() {
  function Entity(sprite, x, y) {
    this.sprite = sprite;
    this.x = x;
    this.y = y;
    this.w = this.sprite.w;
    this.h = this.sprite.h;
  }

  Entity.prototype.isCollision = function(ent) {
    return this.x < ent.x + ent.w && ent.x < this.x + this.w && this.y < ent.y + ent.h && ent.y < this.y + this.h;
  };

  return Entity;

})();
