// Generated by CoffeeScript 1.7.1
var Game;

Game = (function() {
  function Game(width, height) {
    this.width = width;
    this.height = height;
    this.canvas = document.createElement('canvas');
    this.canvas.width = this.width;
    this.canvas.height = this.height;
    this.ctx = this.canvas.getContext('2d');
    this.isOver = false;
    $('body').append(this.canvas);
  }

  Game.prototype.clear = function() {
    return this.ctx.clearRect(0, 0, this.width, this.height);
  };

  Game.prototype.drawSprite = function(sp, x, y) {
    return this.ctx.drawImage(sp.img, sp.x, sp.y, sp.w, sp.h, x, y, sp.w, sp.h);
  };

  return Game;

})();
