// Generated by CoffeeScript 1.7.1
var InputHandler;

InputHandler = (function() {
  function InputHandler() {
    var _this;
    this.down = {};
    _this = this;
    $(document).on('keydown', function(e) {
      return _this.down[e.keyCode] = true;
    });
    $(document).on('keyup', function(e) {
      return delete _this.down[e.keyCode];
    });
  }

  InputHandler.prototype.isDown = function(code) {
    return this.down[code];
  };

  return InputHandler;

})();
