// Generated by CoffeeScript 1.7.1
var Player;

Player = (function() {
  function Player(sprite, x, y) {
    this.sprite = sprite;
    this.x = x;
    this.y = y;
    this.w = this.sprite.w;
    this.h = this.sprite.h;
  }

  return Player;

})();
