// Generated by CoffeeScript 1.7.1
var Sprite;

Sprite = (function() {
  function Sprite(img, x, y, w, h) {
    this.img = img;
    this.x = x;
    this.y = y;
    this.w = w;
    this.h = h;
  }

  return Sprite;

})();
